package com.location.philippweiher.test;

/**
 * Created by philippweiher on 31.07.14.
 */


import com.j256.ormlite.field.DatabaseField;

import java.util.List;


public class StoredAddress {


    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    Integer id;
    @DatabaseField
    String text;
    @DatabaseField
    double latitude;
    @DatabaseField
    double longitude;


    public StoredAddress() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getText() {return text; }

    public void setText(String text) {
        this.text = text;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) { this.longitude = longitude; }


    public StoredAddress(String string, double latitude, double longitude) {
        this.text = string;
        this.latitude = latitude;
        this.longitude = longitude;

    }
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("ID:").append(id);
        sb.append(", ").append("Address:").append(text);

        return sb.toString();
    }

    public static List<StoredAddress> queryForAll() {
        return null;
    }
}